Feat/periodic aggregation
wuespace/telestion-project-daedalus2 pull request #36
Opened 2021-05-15 14:15 UTC by jantischhoefer

### Summary
Removed the database implementation from project-daedalus2.

### Details
Moved the currently working database implementation back to telestion-core and updated config.json

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2021-05-15 14:33 UTC, jantischhoefer commented
We can merge this PR to have a clean working database implementation, but now again back in telestion-core.
I fixed the imports and changed the config.json.
If the PR in telestion-core is merged and daedalus2 uses the new telestion-core, everything should be working as before.

2021-05-15 23:50 UTC, fussel178 requested changes
The indentation is all over the place. :see_no_evil: 
I think, we need some sort of an indentation check for the application site of the project...

For now, can you please indent your modified in a persistent way?

2021-05-15 23:51 UTC, fussel178 commented
And should we resolve the merge conflicts together in the near future? ^^

2021-05-16 07:32 UTC, jantischhoefer commented
> The indentation is all over the place. 
> I think, we need some sort of an indentation check for the application site of the project...
> 
> For now, can you please indent your modified files in a persistent way?

I don't know where that indentation is coming from, because in my editor everything is looking fine.
Is there any settings issue on my side?

2021-05-16 07:43 UTC, jantischhoefer reviewed
io.vertx:vertx-mongo-client can be removed from build.gradle

Indentation will be fixed with spaces instead of tabs?

2021-05-16 07:49 UTC, jantischhoefer reviewed
SystemTPublisher can be uncommented, once telestion-core merged the feat-database-new branch.

2021-05-16 07:53 UTC, jantischhoefer reviewed
Non impact change to SimpleTest.java

2021-05-16 07:56 UTC, jantischhoefer commented
@fussel178 i reviewed the requested changes and tried to fix the indentation. Please see, if the indentation is now correct. Seemed to be a problem with my editor conflicting with the projects .editorconfig

I also resolved the conflicts, because the only conflicts were the correction of the imports for our database verticles, which should be in telestion-core.

2021-05-16 11:34 UTC, pklaschka commented
DO NOT MERGE:
Blocked until https://github.com/wuespace/telestion-core/pull/273 is both merged **and released**.

2021-05-16 12:57 UTC, fussel178 requested changes
Some more stylistic changes. Sorry :see_no_evil:

2021-05-16 12:57 UTC, fussel178 commented on application/conf/config.json
> -	  {
Here the "default" is 2 spaced indented.
And your line is 1 tab and 2 spaces indented.
I think, it's reasonable to stick to 2 spaces indentation for this file.

2021-07-31 20:29 UTC, fussel178 commented
Closing, because code now resides in https://github.com/wuespace/telestion-extension-mongodb.

2021-07-31 20:29 UTC, closed without merging