feat: Add new daedalus.xml mavlink messages
wuespace/telestion-project-daedalus2 pull request #75
Opened 2021-06-12 08:34 UTC by cb0s

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2021-06-21 20:57 UTC, fussel178 requested changes
One little change, otherwise LGTM on the "style" and "repo" side.
For the implementation and coordination side please refer to @pklaschka :see_no_evil:

2021-06-21 20:57 UTC, fussel178 commented on definitions/daedalus.xml
> +		</description>
Little style change :wink: 

```suggestion
		<description>Freetext command input, one command per message.</description>

```

2021-06-22 23:00 UTC, pklaschka approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/75)* status: all files reviewed, 1 unresolved discussion (waiting on @cb0s and @jvpichowski)



<!-- Sent from Reviewable.io -->

2021-06-23 09:52 UTC, pklaschka approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/75#-:-McsHI_p-yRdXxAN3pMx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cb0s and @jvpichowski)



<!-- Sent from Reviewable.io -->

2021-06-23 09:53 UTC, fussel178 approved these changes
LGTM. Thank you for your contribution :palm_tree:

2021-06-23 09:54 UTC, merged